var primitiveTypes = ['Instant', 'Date', 'DateTime', 'Decimal', 'Boolean', 'Integer', 'String', 'Uri', 'Base64Binary', 'Code', 'Id', 'Oid', 'Uuid', 'markdown', 'unsignedInt', 'positiveInt'];
var choiceTypes = ['Integer', 'Decimal', 'DateTime', 'Date', 'Instant', 'String', 'Uri', 'Boolean', 'Code', 'base64Binary', 'Coding', 'CodeableConcept', 'Attachment', 'Identifier', 'Quantity', 'Range', 'Period', 'Ratio', 'HumanName', 'Address', 'Reference', 'Signature', 'Timing', 'ContactPoint', 'Markdown'];

var util = {
    PrimitiveTypes: primitiveTypes,
    ChoiceTypes: choiceTypes,
    FindElement: function(elementPath, profiles) {
        var elementPathSplit = elementPath.split('.');
        var profile = profiles[elementPathSplit[0]];

        if (elementPathSplit[elementPathSplit.length-1] == 'extension') {
            return {
                path: elementPath,
                definition: {
                    short: 'extension',
                    formal: 'extension',
                    min: 0,
                    max: '*',
                    type: [{
                        code: 'extension'
                    }]
                }
            };
        };

        var profileElementPath = elementPath;
        var elementPathSplit = elementPath.split('.');
        var leafPath = elementPathSplit[elementPathSplit.length-1];
        var selectedChoiceType = null;

        if (util.ChoiceElements[leafPath]) {
            for (var i in choiceTypes) {
                var choiceType = choiceTypes[i];
                var choiceIndex = leafPath.length - choiceType.length;

                if (choiceIndex > 0 && leafPath.indexOf(choiceType) == choiceIndex) {
                    elementPathSplit[elementPathSplit.length-1] = leafPath.substring(0, leafPath.length - choiceType.length) + '[x]';
                    profileElementPath = elementPathSplit.join('.');
                    selectedChoiceType = choiceType;
                    break;
                }
            }
        }

        if (profile) {
            for (var i in profile.snapshot.element) {
                var element = profile.snapshot.element[i];

                if (element.path == profileElementPath) {
                    if (profileElementPath != elementPath && element.definition) {
                        // TODO: Should figure out a better way not to modify the base profile (since JSON.parse/stringify is a little costly)...
                        // Maybe a completely custom return type for FindElement
                        element = JSON.parse(JSON.stringify(element));
                        element.definition.type = [{
                            code: choiceType
                        }] ;
                    }

                    return element;
                }
            }
        }

        return;
    },

    IsPrimitive: function(elementType) {
        if (!elementType) {
            return false;
        }

        for (var x in primitiveTypes) {
            var primitiveType = primitiveTypes[x];

            if (primitiveType.toLowerCase() == elementType.toLowerCase()) {
                return true;
            }
        }

        return false;
    },

    ChoiceElements: {
        "valueBoolean": "boolean",
        "valueInteger": "integer",
        "valueDecimal": "decimal",
        "valueBase64Binary": "base64Binary",
        "valueInstant": "instant",
        "valueString": "string",
        "valueUri": "uri",
        "valueDate": "date",
        "valueDateTime": "dateTime",
        "valueCode": "code",
        "valueAttachment": "Attachment",
        "valueIdentifier": "Identifier",
        "valueCodeableConcept": "CodeableConcept",
        "valueCoding": "Coding",
        "valueQuantity": "Quantity",
        "valueRange": "Range",
        "valuePeriod": "Period",
        "valueRatio": "Ratio",
        "valueResource": "Reference",
        "valueSampledDate": "SampledDate",
        "valueHumanName": "HumanName",
        "valueAddress": "Address",
        "valueContactPoint": "ContactPoint",
        "timingBoolean": "boolean",
        "timingInteger": "integer",
        "timingDecimal": "decimal",
        "timingBase64Binary": "base64Binary",
        "timingInstant": "instant",
        "timingString": "string",
        "timingUri": "uri",
        "timingDate": "date",
        "timingDateTime": "dateTime",
        "timingCode": "code",
        "timingAttachment": "Attachment",
        "timingIdentifier": "Identifier",
        "timingCodeableConcept": "CodeableConcept",
        "timingCoding": "Coding",
        "timingQuantity": "Quantity",
        "timingRange": "Range",
        "timingPeriod": "Period",
        "timingRatio": "Ratio",
        "timingResource": "Reference",
        "timingSampledDate": "SampledDate",
        "timingHumanName": "HumanName",
        "timingAddress": "Address",
        "timingContactPoint": "ContactPoint",
        "onsetBoolean": "boolean",
        "onsetInteger": "integer",
        "onsetDecimal": "decimal",
        "onsetBase64Binary": "base64Binary",
        "onsetInstant": "instant",
        "onsetString": "string",
        "onsetUri": "uri",
        "onsetDate": "date",
        "onsetDateTime": "dateTime",
        "onsetCode": "code",
        "onsetAttachment": "Attachment",
        "onsetIdentifier": "Identifier",
        "onsetCodeableConcept": "CodeableConcept",
        "onsetCoding": "Coding",
        "onsetQuantity": "Quantity",
        "onsetRange": "Range",
        "onsetPeriod": "Period",
        "onsetRatio": "Ratio",
        "onsetResource": "Reference",
        "onsetSampledDate": "SampledDate",
        "onsetHumanName": "HumanName",
        "onsetAddress": "Address",
        "onsetContactPoint": "ContactPoint",
        "abatementBoolean": "boolean",
        "abatementInteger": "integer",
        "abatementDecimal": "decimal",
        "abatementBase64Binary": "base64Binary",
        "abatementInstant": "instant",
        "abatementString": "string",
        "abatementUri": "uri",
        "abatementDate": "date",
        "abatementDateTime": "dateTime",
        "abatementCode": "code",
        "abatementAttachment": "Attachment",
        "abatementIdentifier": "Identifier",
        "abatementCodeableConcept": "CodeableConcept",
        "abatementCoding": "Coding",
        "abatementQuantity": "Quantity",
        "abatementRange": "Range",
        "abatementPeriod": "Period",
        "abatementRatio": "Ratio",
        "abatementResource": "Reference",
        "abatementSampledDate": "SampledDate",
        "abatementHumanName": "HumanName",
        "abatementAddress": "Address",
        "abatementContactPoint": "ContactPoint",
        "diagnosticBoolean": "boolean",
        "diagnosticInteger": "integer",
        "diagnosticDecimal": "decimal",
        "diagnosticBase64Binary": "base64Binary",
        "diagnosticInstant": "instant",
        "diagnosticString": "string",
        "diagnosticUri": "uri",
        "diagnosticDate": "date",
        "diagnosticDateTime": "dateTime",
        "diagnosticCode": "code",
        "diagnosticAttachment": "Attachment",
        "diagnosticIdentifier": "Identifier",
        "diagnosticCodeableConcept": "CodeableConcept",
        "diagnosticCoding": "Coding",
        "diagnosticQuantity": "Quantity",
        "diagnosticRange": "Range",
        "diagnosticPeriod": "Period",
        "diagnosticRatio": "Ratio",
        "diagnosticResource": "Reference",
        "diagnosticSampledDate": "SampledDate",
        "diagnosticHumanName": "HumanName",
        "diagnosticAddress": "Address",
        "diagnosticContactPoint": "ContactPoint",
        "bornBoolean": "boolean",
        "bornInteger": "integer",
        "bornDecimal": "decimal",
        "bornBase64Binary": "base64Binary",
        "bornInstant": "instant",
        "bornString": "string",
        "bornUri": "uri",
        "bornDate": "date",
        "bornDateTime": "dateTime",
        "bornCode": "code",
        "bornAttachment": "Attachment",
        "bornIdentifier": "Identifier",
        "bornCodeableConcept": "CodeableConcept",
        "bornCoding": "Coding",
        "bornQuantity": "Quantity",
        "bornRange": "Range",
        "bornPeriod": "Period",
        "bornRatio": "Ratio",
        "bornResource": "Reference",
        "bornSampledDate": "SampledDate",
        "bornHumanName": "HumanName",
        "bornAddress": "Address",
        "bornContactPoint": "ContactPoint",
        "deceasedBoolean": "boolean",
        "deceasedInteger": "integer",
        "deceasedDecimal": "decimal",
        "deceasedBase64Binary": "base64Binary",
        "deceasedInstant": "instant",
        "deceasedString": "string",
        "deceasedUri": "uri",
        "deceasedDate": "date",
        "deceasedDateTime": "dateTime",
        "deceasedCode": "code",
        "deceasedAttachment": "Attachment",
        "deceasedIdentifier": "Identifier",
        "deceasedCodeableConcept": "CodeableConcept",
        "deceasedCoding": "Coding",
        "deceasedQuantity": "Quantity",
        "deceasedRange": "Range",
        "deceasedPeriod": "Period",
        "deceasedRatio": "Ratio",
        "deceasedResource": "Reference",
        "deceasedSampledDate": "SampledDate",
        "deceasedHumanName": "HumanName",
        "deceasedAddress": "Address",
        "deceasedContactPoint": "ContactPoint",
        "asNeededBoolean": "boolean",
        "asNeededInteger": "integer",
        "asNeededDecimal": "decimal",
        "asNeededBase64Binary": "base64Binary",
        "asNeededInstant": "instant",
        "asNeededString": "string",
        "asNeededUri": "uri",
        "asNeededDate": "date",
        "asNeededDateTime": "dateTime",
        "asNeededCode": "code",
        "asNeededAttachment": "Attachment",
        "asNeededIdentifier": "Identifier",
        "asNeededCodeableConcept": "CodeableConcept",
        "asNeededCoding": "Coding",
        "asNeededQuantity": "Quantity",
        "asNeededRange": "Range",
        "asNeededPeriod": "Period",
        "asNeededRatio": "Ratio",
        "asNeededResource": "Reference",
        "asNeededSampledDate": "SampledDate",
        "asNeededHumanName": "HumanName",
        "asNeededAddress": "Address",
        "asNeededContactPoint": "ContactPoint",
        "reasonBoolean": "boolean",
        "reasonInteger": "integer",
        "reasonDecimal": "decimal",
        "reasonBase64Binary": "base64Binary",
        "reasonInstant": "instant",
        "reasonString": "string",
        "reasonUri": "uri",
        "reasonDate": "date",
        "reasonDateTime": "dateTime",
        "reasonCode": "code",
        "reasonAttachment": "Attachment",
        "reasonIdentifier": "Identifier",
        "reasonCodeableConcept": "CodeableConcept",
        "reasonCoding": "Coding",
        "reasonQuantity": "Quantity",
        "reasonRange": "Range",
        "reasonPeriod": "Period",
        "reasonRatio": "Ratio",
        "reasonReference": "Reference",
        "reasonSampledDate": "SampledDate",
        "reasonHumanName": "HumanName",
        "reasonAddress": "Address",
        "reasonContactPoint": "ContactPoint",
        "appliesBoolean": "boolean",
        "appliesInteger": "integer",
        "appliesDecimal": "decimal",
        "appliesBase64Binary": "base64Binary",
        "appliesInstant": "instant",
        "appliesString": "string",
        "appliesUri": "uri",
        "appliesDate": "date",
        "appliesDateTime": "dateTime",
        "appliesCode": "code",
        "appliesAttachment": "Attachment",
        "appliesIdentifier": "Identifier",
        "appliesCodeableConcept": "CodeableConcept",
        "appliesCoding": "Coding",
        "appliesQuantity": "Quantity",
        "appliesRange": "Range",
        "appliesPeriod": "Period",
        "appliesRatio": "Ratio",
        "appliesReference": "Reference",
        "appliesSampledDate": "SampledDate",
        "appliesHumanName": "HumanName",
        "appliesAddress": "Address",
        "appliesContactPoint": "ContactPoint",
        "authorityBoolean": "boolean",
        "authorityInteger": "integer",
        "authorityDecimal": "decimal",
        "authorityBase64Binary": "base64Binary",
        "authorityInstant": "instant",
        "authorityString": "string",
        "authorityUri": "uri",
        "authorityDate": "date",
        "authorityDateTime": "dateTime",
        "authorityCode": "code",
        "authorityAttachment": "Attachment",
        "authorityIdentifier": "Identifier",
        "authorityCodeableConcept": "CodeableConcept",
        "authorityCoding": "Coding",
        "authorityQuantity": "Quantity",
        "authorityRange": "Range",
        "authorityPeriod": "Period",
        "authorityRatio": "Ratio",
        "authorityReference": "Reference",
        "authoritySampledDate": "SampledDate",
        "authorityHumanName": "HumanName",
        "authorityAddress": "Address",
        "authorityContactPoint": "ContactPoint",
        "multipleBirthBoolean": "boolean",
        "multipleBirthInteger": "integer",
        "multipleBirthDecimal": "decimal",
        "multipleBirthBase64Binary": "base64Binary",
        "multipleBirthInstant": "instant",
        "multipleBirthString": "string",
        "multipleBirthUri": "uri",
        "multipleBirthDate": "date",
        "multipleBirthDateTime": "dateTime",
        "multipleBirthCode": "code",
        "multipleBirthAttachment": "Attachment",
        "multipleBirthIdentifier": "Identifier",
        "multipleBirthCodeableConcept": "CodeableConcept",
        "multipleBirthCoding": "Coding",
        "multipleBirthQuantity": "Quantity",
        "multipleBirthRange": "Range",
        "multipleBirthPeriod": "Period",
        "multipleBirthRatio": "Ratio",
        "multipleBirthReference": "Reference",
        "multipleBirthSampledDate": "SampledDate",
        "multipleBirthHumanName": "HumanName",
        "multipleBirthAddress": "Address",
        "multipleBirthContactPoint": "ContactPoint",
        "exampleBoolean": "boolean",
        "exampleInteger": "integer",
        "exampleDecimal": "decimal",
        "exampleBase64Binary": "base64Binary",
        "exampleInstant": "instant",
        "exampleString": "string",
        "exampleUri": "uri",
        "exampleDate": "date",
        "exampleDateTime": "dateTime",
        "exampleCode": "code",
        "exampleAttachment": "Attachment",
        "exampleIdentifier": "Identifier",
        "exampleCodeableConcept": "CodeableConcept",
        "exampleCoding": "Coding",
        "exampleQuantity": "Quantity",
        "exampleRange": "Range",
        "examplePeriod": "Period",
        "exampleRatio": "Ratio",
        "exampleReference": "Reference",
        "exampleSampledDate": "SampledDate",
        "exampleHumanName": "HumanName",
        "exampleAddress": "Address",
        "exampleContactPoint": "ContactPoint",
        "referenceBoolean": "boolean",
        "referenceInteger": "integer",
        "referenceDecimal": "decimal",
        "referenceBase64Binary": "base64Binary",
        "referenceInstant": "instant",
        "referenceString": "string",
        "referenceUri": "uri",
        "referenceDate": "date",
        "referenceDateTime": "dateTime",
        "referenceCode": "code",
        "referenceAttachment": "Attachment",
        "referenceIdentifier": "Identifier",
        "referenceCodeableConcept": "CodeableConcept",
        "referenceCoding": "Coding",
        "referenceQuantity": "Quantity",
        "referenceRange": "Range",
        "referencePeriod": "Period",
        "referenceRatio": "Ratio",
        "referenceReference": "Reference",
        "referenceSampledDate": "SampledDate",
        "referenceHumanName": "HumanName",
        "referenceAddress": "Address",
        "referenceContactPoint": "ContactPoint",
        "answerBoolean": "boolean",
        "answerInteger": "integer",
        "answerDecimal": "decimal",
        "answerBase64Binary": "base64Binary",
        "answerInstant": "instant",
        "answerString": "string",
        "answerUri": "uri",
        "answerDate": "date",
        "answerDateTime": "dateTime",
        "answerCode": "code",
        "answerAttachment": "Attachment",
        "answerIdentifier": "Identifier",
        "answerCodeableConcept": "CodeableConcept",
        "answerCoding": "Coding",
        "answerQuantity": "Quantity",
        "answerRange": "Range",
        "answerPeriod": "Period",
        "answerRatio": "Ratio",
        "answerReference": "Reference",
        "answerSampledDate": "SampledDate",
        "answerHumanName": "HumanName",
        "answerAddress": "Address",
        "answerContactPoint": "ContactPoint",
        "dataBoolean": "boolean",
        "dataInteger": "integer",
        "dataDecimal": "decimal",
        "dataBase64Binary": "base64Binary",
        "dataInstant": "instant",
        "dataString": "string",
        "dataUri": "uri",
        "dataDate": "date",
        "dataDateTime": "dateTime",
        "dataCode": "code",
        "dataAttachment": "Attachment",
        "dataIdentifier": "Identifier",
        "dataCodeableConcept": "CodeableConcept",
        "dataCoding": "Coding",
        "dataQuantity": "Quantity",
        "dataRange": "Range",
        "dataPeriod": "Period",
        "dataRatio": "Ratio",
        "dataReference": "Reference",
        "dataSampledDate": "SampledDate",
        "dataHumanName": "HumanName",
        "dataAddress": "Address",
        "dataContactPoint": "ContactPoint",
        "collectedBoolean": "boolean",
        "collectedInteger": "integer",
        "collectedDecimal": "decimal",
        "collectedBase64Binary": "base64Binary",
        "collectedInstant": "instant",
        "collectedString": "string",
        "collectedUri": "uri",
        "collectedDate": "date",
        "collectedDateTime": "dateTime",
        "collectedCode": "code",
        "collectedAttachment": "Attachment",
        "collectedIdentifier": "Identifier",
        "collectedCodeableConcept": "CodeableConcept",
        "collectedCoding": "Coding",
        "collectedQuantity": "Quantity",
        "collectedRange": "Range",
        "collectedPeriod": "Period",
        "collectedRatio": "Ratio",
        "collectedReference": "Reference",
        "collectedSampledDate": "SampledDate",
        "collectedHumanName": "HumanName",
        "collectedAddress": "Address",
        "collectedContactPoint": "ContactPoint"
    }
};

module.exports = util;